### PR TITLE
* First commit: Mini-project 2 | Random user API

### PR DESCRIPTION
**Pull request by AroLalayan**

### CODE REVIEW

**Comment by posadvladimir** [comment]
1. Method Date.prototype.customFormatDate is hard to read and understand.
2. It is better to use 'let' 'const' to declare variables. (ES6)

**Comment by elen-s17** [comment]
1. The app is working as intended, the style is very nice.
2. Can add a header describing what it the app is doing.

**Comment by AroLalayan** [comment]
Thanks for feedback.

@posadvladimir 

1) I have made the appropriate changes.
2) Done

@elen-s17 
1) Thank you)))
2) Done, I add the title above the card.

You can check the new version here.
https://github.com/AroLalayan/random-user-api-arayik-lalayan/pull/2

**Comment by elen-s17** [comment]
I have reviewed the updated code. Project result: success

**Comment by posadvladimir** [comment]
Everything is good
Result: Success

**Pull request merged**
